server:
  port: 11314

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/muke?characterEncoding=utf-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  file: myapp.log
#  path: /Users/circleus/Documents/tmp
