package com.anhe.mapper;

import com.anhe.entity.CloseoutInfo;
import com.anhe.entity.CloseoutInfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface CloseoutInfoMapper {

    CloseoutInfo fuzzyQueryByValue(@Param("content") String content);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeout_info
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    long countByExample(CloseoutInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeout_info
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    int deleteByExample(CloseoutInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeout_info
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeout_info
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    int insert(CloseoutInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeout_info
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    int insertSelective(CloseoutInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeout_info
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    List<CloseoutInfo> selectByExample(CloseoutInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeout_info
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    CloseoutInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeout_info
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") CloseoutInfo record, @Param("example") CloseoutInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeout_info
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    int updateByExample(@Param("record") CloseoutInfo record, @Param("example") CloseoutInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeout_info
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    int updateByPrimaryKeySelective(CloseoutInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeout_info
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    int updateByPrimaryKey(CloseoutInfo record);
}