package com.anhe.entity;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

public class CloseoutInfo implements Serializable {
    private static SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeout_info.id
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeout_info.construct
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    private String construct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeout_info.value
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeout_info.pickup_num
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    private Integer pickupNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeout_info.trackings
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    private String trackings;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeout_info.create_time
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeout_info.update_time
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeout_info.del_status
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    private Boolean delStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table closeout_info
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeout_info.id
     *
     * @return the value of closeout_info.id
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeout_info.id
     *
     * @param id the value for closeout_info.id
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeout_info.construct
     *
     * @return the value of closeout_info.construct
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public String getConstruct() {
        return construct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeout_info.construct
     *
     * @param construct the value for closeout_info.construct
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public void setConstruct(String construct) {
        this.construct = construct == null ? null : construct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeout_info.value
     *
     * @return the value of closeout_info.value
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeout_info.value
     *
     * @param value the value for closeout_info.value
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeout_info.pickup_num
     *
     * @return the value of closeout_info.pickup_num
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public Integer getPickupNum() {
        return pickupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeout_info.pickup_num
     *
     * @param pickupNum the value for closeout_info.pickup_num
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public void setPickupNum(Integer pickupNum) {
        this.pickupNum = pickupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeout_info.trackings
     *
     * @return the value of closeout_info.trackings
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public String getTrackings() {
        return trackings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeout_info.trackings
     *
     * @param trackings the value for closeout_info.trackings
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public void setTrackings(String trackings) {
        this.trackings = trackings == null ? null : trackings.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeout_info.create_time
     *
     * @return the value of closeout_info.create_time
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeout_info.create_time
     *
     * @param createTime the value for closeout_info.create_time
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeout_info.update_time
     *
     * @return the value of closeout_info.update_time
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeout_info.update_time
     *
     * @param updateTime the value for closeout_info.update_time
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeout_info.del_status
     *
     * @return the value of closeout_info.del_status
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public Boolean getDelStatus() {
        return delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeout_info.del_status
     *
     * @param delStatus the value for closeout_info.del_status
     *
     * @mbg.generated Thu Apr 11 09:54:15 CST 2019
     */
    public void setDelStatus(Boolean delStatus) {
        this.delStatus = delStatus;
    }
}